### ISSUE TITLE
TODO-List

### ISSUE THREAD

**Issue by FoxBanri** [AlexRockstroh/projectMultimodal#1]
- [x] Rahmen für Spielende-Nachricht
- [x] Nach Spielende Eingaben blockieren
- [x] Spielende-Nachricht zu groß für das Textfeld --> Textfeld-Größe anpassen

**Comment by AlexRockstroh** [comment]
- [ ] Layout mit Philip's Device testen

**Comment by AlexRockstroh** [comment]
- [ ] Layout allgemein verfeineren
